# Generated by Django 3.1.5 on 2021-01-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210115_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='apelido',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='carros',
            name='observacao',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
