# Generated by Django 3.1.5 on 2021-01-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210115_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carros',
            old_name='ano',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='carros',
            old_name='marca',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='carros',
            old_name='modelo',
            new_name='sobrenome',
        ),
    ]
