# Generated by Django 3.1.5 on 2021-01-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210115_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carros',
            new_name='Pessoa',
        ),
    ]
